# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicMaker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicMaker
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'GoogleSignIn'

end
